config/routes.rb
Strangerdanger::Application.routes.draw do
  resources :users, :user_sessions, :songs, :parts, :comments, :requests, :assignments
    match 'login' => 'user_sessions#new', :as => :login
    match 'logout' => 'user_sessions#destroy', :as => :logout
    match '/backyard',    :to => 'pages#backyard'
    match '/admin',    :to => 'pages#admin'
    
    root :to => 'pages#home'
    

end

app/models/part.rb
class Part < ActiveRecord::Base
  belongs_to :assigments
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
  
  rescue_from 'Acl9::AccessDenied', :with => :access_denied
  
  access_control do   
    allow :admin
  end
  
  def index
    @parts = Part.all
  end
  
  def new
    @part = Part.new
  end
  
  def create
    @part = Part.new(params[:part])
    respond_to do |format|
      if @part.save
        format.html { redirect_to(:parts, :notice => 'Registration successfull.') }
        format.xml  { render :xml => @part, :status => :created, :location => @part }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @part.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def edit
    @part = Part.find(params[:id])
  end
  
  def update
    @part = Part.find(params[:id])

    respond_to do |format|
      if @part.update_attributes(params[:part])
        format.html { redirect_to(@part, :notice => 'Part was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @part.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def show
    @part = Part.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @part }
    end
  end

  def destroy
    @part = Part.find(params[:id])
    @assignments = Assignment.all
    for assignment in @assignments
      if assignment.part_id == @part.id
        assignment.destroy
      end
    end
    @part.destroy

    respond_to do |format|
      format.html { redirect_to(admin_path) }
      format.xml  { head :ok }
    end
  end
  
  def access_denied
    redirect_to backyard_path
  end
  
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/views/parts/_form.html.erb
<%= form_for(@part) do |f| %>
  <% if @part.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@part.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @part.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/parts/edit.html.erb
<h1>Editing part</h1>

<%= render 'form' %>

app/views/parts/index.html.erb
<h1>Listing parts</h1>
<p id="notice"><%= notice %></p>
<table>
  <tr>
    <th>Name</th>
  </tr>

<% @parts.each do |part| %>
  <tr>
    <td><%= part.name %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Part', new_part_path %>

app/views/parts/new.html.erb
<h1>New part</h1>

<%= render 'form' %>

app/views/parts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @part.name %>
</p>

<%= link_to 'Edit', edit_part_path(@part) %> |
<%= link_to 'Back', parts_path %>