config/routes.rb
Strangerdanger::Application.routes.draw do
  resources :users, :user_sessions, :songs, :parts, :comments, :requests, :assignments
    match 'login' => 'user_sessions#new', :as => :login
    match 'logout' => 'user_sessions#destroy', :as => :logout
    match '/backyard',    :to => 'pages#backyard'
    match '/admin',    :to => 'pages#admin'
    
    root :to => 'pages#home'
    

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  has_one :user
  has_one :song
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  rescue_from 'Acl9::AccessDenied', :with => :access_denied
  
  access_control do   
    allow :admin
    allow logged_in, :to => [:create, :new] 
  end
  
  def index
    @comments = Comment.all
    @songs = Song.all
    @users = User.all
  end
  
  def new
    @comment = Comment.new
  end
  
  def create
    @comment = Comment.new(params[:comment])
    respond_to do |format|
      if @comment.save
        format.html { redirect_to(:comments, :notice => 'Registration successfull.') }
        format.xml  { render :xml => @comment, :status => :created, :location => @comment }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @comment.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def edit
    @comment = Comment.find(params[:id])
  end
  
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to(@comment, :notice => 'Comment was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @comment.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @comment }
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to(admin_path) }
      format.xml  { head :ok }
    end
  end
  
  def access_denied
    redirect_to backyard_path
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :song_id %><br />
    <%= f.text_field :song_id %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>
<p id="notice"><%= notice %></p>
<table>
  <tr>
    <th>Song</th>
    <th>User</th>
    <th>Content</th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    	<td>
			<% @songs.each do |song| %>
			<% if song.id == comment.song_id %>
				<%= song.name %>
			<% end %>	
			<% end %>
		</td>
		<td>
		   	<% @users.each do |user| %>
				<% if comment.user_id == user.id %>
		    		<%= user.username %>
				<% end %>
		 	<% end %>
		</td>
	<td><%= comment.content %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Song:</b>
  <%= @comment.song_id %>
</p>

<p>
  <b>User:</b>
  <%= @comment.user_id %>
</p>

<p>
  <b>Content:</b>
  <%= @comment.content %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>