config/routes.rb
Strangerdanger::Application.routes.draw do
  resources :users, :user_sessions, :songs, :parts, :comments, :requests, :assignments
    match 'login' => 'user_sessions#new', :as => :login
    match 'logout' => 'user_sessions#destroy', :as => :logout
    match '/backyard',    :to => 'pages#backyard'
    match '/admin',    :to => 'pages#admin'
    
    root :to => 'pages#home'
    

end

app/views/pages/_form.html.erb
<%= form_for(@request) do |f| %>
  <% if @request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@request.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
	<%= f.select :song, @songs.map {|r| [r.name, r.id]} %>
  </div>
  <div class="field">
	<%= f.select :part, @parts.map {|r| [r.name, r.id]} %>
  </div>
  <div class="field">
    <%= f.label :comments %><br />
    <%= f.text_area :comments %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/_form_backyard.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


	<% @songs.each do |song| %>
		<% if song.current == true%>
			<%= f.hidden_field :song_id, :value => song.id %>
		<% end %>
	<% end %>
	
	<%= f.hidden_field :user_id, :value => current_user.id %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/_form_home.html.erb
<%= form_for(@request) do |f| %>
  <% if @request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@request.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
	<%= f.select :song, @songs.map {|r| [r.name, r.id]} %>
  </div>
  <div class="field">
	<%= f.select :part, @parts.map {|r| [r.name, r.id]} %>
  </div>
  <div class="field">
    <%= f.label :comments %><br />
    <%= f.text_area :comments %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/admin.html.erb
<h1>Admin Page</h1>

<section class="assignments">
	<h1>Assignments</h1>
	<table>
		<colgroup>
			<col class="song">
			<col class="part">
			<col class="user">
		</colgroup>
		<thead>
			<tr>
				<th>Song</th>
				<th>Part</th>
				<th>User</th>
				<th></th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<% if @assignments && @assignments.size != 0 %>
			<% @assignments.each do |assignment| %>
			<tr>
				<% if !assignment.song_id.nil? && !assignment.part_id.nil? && !assignment.part_id.nil? %>
				<td><%= song(assignment.song_id) %></td>
				<td><%= part(assignment.part_id) %></td>
				<td><%= user(assignment.user_id) %></td>
				<td><%= link_to("Edit", edit_assignment_path(assignment)) %></td>
				<td><%= button_to 'Destroy', assignment_path(assignment), :method => :delete, :confirm => 'Are you sure you want to destroy this assignment?' %></td>
				<% end %>
			</tr>
			<% end %>
			<% else %>
				<td colspan="4">No Assignments yet</td>
			<% end %>
		</tbody>
	</table>
	<%= link_to("New Assignment", new_assignment_path) %>
</section>

<section class="songs">
	<h1>Songs</h1>
	<table>
		<colgroup>
			<col class="name">
			<col class="file">
			<col class="active">
			<col class="recorded">
			<col class="current">
		</colgroup>
		<thead>
			<tr>
				<th>Name</th>
				<th>File</th>
				<th>Active</th>
				<th>Recorded</th>
				<th>Current</th>
				<th></th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<% if @songs && @songs.size != 0 %>
			<% @songs.each do |song| %>
			<tr>
				<% if !song.name.nil? && !song.file.nil? && !song.active.nil? && !song.recorded.nil? && !song.current.nil? %>
				<td><%= song.name %></td>
				<td><%= song.file %></td>
				<td><%= song.active %></td>
				<td><%= song.recorded %></td>
				<td><%= song.current %></td>
				<td><%= link_to("Edit", edit_song_path(song)) %></td>
				<td><%= button_to 'Destroy', song_path(song), :method => :delete, :confirm => 'Are you sure you want to destroy this song?' %></td>
				<% end %>
			</tr>
			<% end %>
			<% else %>
				<td colspan="6">No Songs yet</td>
			<% end %>
		</tbody>
	</table>
	<%= link_to("New Song", new_song_path) %>
</section>

<section class="parts">
	<h1>Parts</h1>
	<table>
		<colgroup>
			<col class="name" />
		</colgroup>
		<thead>
			<tr>
				<th>Name</th>
				<th></th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<% if @parts && @parts.size != 0 %>
			<% @parts.each do |part| %>
			<tr>
				<% if !part.name.nil? %>
				<td><%= part.name %></td>
				<td><%= link_to("Edit", edit_part_path(part)) %></td>
				<td><%= button_to 'Destroy', part_path(part), :method => :delete, :confirm => 'Are you sure you want to destroy this part?' %></td>
				<% end %>
			</tr>
			<% end %>
			<% else %>
				<td colspan="2">No Parts yet</td>
			<% end %>
		</tbody>
	</table>
	<%= link_to("New Part", new_part_path) %>
</section>

<section class="users">
	<h1>Users</h1>
	<table>
		<colgroup>
			<col class="name" />
			<col class="email" />
		</colgroup>
		<thead>
			<tr>
				<th>Name</th>
				<th>Email</th>
				<th></th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<% if @users && @users.size != 0 %>
			<% @users.each do |user| %>
			<tr>
				<% if !user.username.nil? && !user.email.nil? %>
				<td><%= user.username %></td>
				<td><%= user.email %></td>
				<td><%= link_to("Edit", edit_user_path(user)) %></td>
				<td><%= button_to 'Destroy', user_path(user), :method => :delete, :confirm => 'Are you sure you want to destroy this user?' %></td>
				<% end %>
			</tr>
			<% end %>
			<% else %>
				<td colspan="3">No Users yet</td>
			<% end %>
		</tbody>
	</table>
	<%= link_to("New User", new_user_path) %>
</section>

<section class="comments">
	<h1>Comments</h1>
	<table>
		<colgroup>
			<col class="song" />
			<col class="user" />
			<col class="content" />
		</colgroup>
		<thead>
			<tr>
				<th>Song</th>
				<th>User</th>
				<th>Content</th>
				<th></th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<% if @comments && @comments.size != 0 %>
				<% @comments.each do |comment| %>

			<tr>
				<td>
				<% @songs.each do |song| %>
					<% if song.id == comment.song_id %>
						<%= song.name %>
					<% end %>
				<% end %>
				</td>
				<td>
				<% @users.each do |user| %>
					<% if user.id == comment.user_id %>
						<%= user.username %>
					<% end %>
				<% end %>
				</td>
				<td><%= comment.content %></td>
				<td><%= link_to("Edit", edit_comment_path(comment)) %></td>
				<td><%= button_to 'Destroy', comment_path(comment), :method => :delete, :confirm => 'Are you sure you want to destroy this comment?' %></td>
			</tr>
				<% end %>
			<% else %>
				<td colspan="4">No Comments yet</td>
			<% end %>
		</tbody>
	</table>
</section>

<section class="requests">
	<h1>Requests</h1>
	<table>
		<colgroup>
			<col class="name" />
			<col class="email" />
			<col class="song" />
			<col class="part" />
			<col class="comments" />
		</colgroup>
		<thead>
			<tr>
				<th>Name</th>
				<th>Email</th>
				<th>Song</th>
				<th>Part</th>
				<th>Comments</th>
				<th></th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<% if @requests && @requests.size != 0 %>
			<% @requests.each do |request| %>
			<tr>
				<% if !request.name.nil? && !request.email.nil? && !request.song.nil? && !request.part.nil? && !request.comments.nil? %>
				<td><%= request.name %></td>
				<td><%= request.email %></td>
				<td><%= request.song %></td>
				<td><%= request.part %></td>
				<td><%= request.comments %></td>
				<td><%= link_to("Edit", edit_request_path(request)) %></td>
				<td><%= button_to 'Destroy', request_path(request), :method => :delete, :confirm => 'Are you sure you want to destroy this request?' %></td>
				<% end %>
			</tr>
			<% end %>
			<% else %>
				<td colspan="6">No Requests yet</td>
			<% end %>
		</tbody>
	</table>
</section>

app/views/pages/backyard.html.erb
<h1>Welcome to the Backyard!</h1>

<section class="first-time-text">
	<p>Welcome to the backyard. If you're here, then you recorded a track on one of the project's songs. This section is so you can see the progress that's being made in recording and mixing, as well as leave input an collaborate as much or as little as you'd like in the production process. Take a look around, get to know what's been done, who did what, and make yourself at home!</p>
</section>

<section class="songs">
	<article class="current-song">
		<h1>Current Track Being Tinkered With</h1>
		<div id="mp3Player" data-folder="music" class="player">

			<audio id="mp3Player-player">
				<source id="mp3Player-mp3" src="" />
				<p class="no-html5">Your browser doesn\'t support HTML5 audio</p>
			</audio>

			<div id="mp3Player-controls" class="mp3Player-group playerControls">
				<div id="mp3Player-buttons-container">
					<button id="mp3Player-prev" class="mp3controls disabled">Prev</button>
					<div id="mp3Player-play-pause">
						<button id="mp3Player-play" class="mp3controls">Play</button>
						<button id="mp3Player-pause" class="mp3controls display-off">Pause</button>
					</div>
					<button id="mp3Player-next" class="mp3controls disabled">Next</button>
				</div>

				<div id="mp3Player-progress-container" class="mp3Player-group progressContainer">
					<span id="mp3Player-currentTime"></span>
					<div id="mp3Player-progress" class="loaded"></div>
					<span id="mp3Player-remainingTime"></span>
				</div>

				<div id="mp3Player-volume-container" class="mp3Player-group">
					<span id="mp3Player-min-volume"></span>
					<div id="mp3Player-volume"></div>
					<span id="mp3Player-max-volume"></span>
				</div>
			</div>

			<% if @songs && @songs.size != 0 %>
			<table id="mp3Player-table">
				<thead>
				<tr>
					<th>Song</th>
					<th>Part(s)</th>
				</tr>
				</thead>
				<tbody>
			<% @songs.each do |song| %>
			<% if song.current == true %>
				<tr class="song" data-file="<%= song.file %>">
					<td class="name"><%= song.name %></td>
					<td>
						<ul>
				<% if @assignments && @assignments.size != 0 %>
				<% @assignments.each do |assignment| %>
				<% if assignment.song_id == song.id && assignment.user_id != 1 %>
					<li class="part"><%= part(assignment.part_id) %></li>
				<% end %>
				<% end %>
				<% end %>
						</ul>
					</td>
				</tr>
			<% end %>
			<% end %>
			</table>
			<% end %>
			</tbody>
		</div>
		<div class="parts">
			<% @songs.each do |song| %>
			<% if song.current == true %>
			<h2>Parts already recorded</h2>
			<ul>
			<% if @assignments && @assignments.size != 0 %>
			<% @assignments.each do |assignment| %>
			<% if assignment.song_id == song.id && assignment.user_id != 1 %>
				<li><span class="part"><%= part(assignment.part_id) %></span> <span class="user"><%= part(assignment.user_id) %></span></li>
			<% end %>
			<% end %>
			<% end %>
			</ul>
			<% end %>
			<% end %>
		</div>
		<div class="comments">
			<% if @comments && @comments.size != 0 %>
			<h1>Comments</h1>
			<div class="comment-input">
				<h2>Leave a comment</h2>
				<%= render "form_backyard" %>
			</div>
			<div class="comment-list">
				<% @songs.each do |song| %>
				<% if song.current == true %>
				<% if @songcomments && @songcomments.size != 0 %>
				<h2><span class="number"><%= @songcomments.size %></span> Comments on <span class="song"><%= song.name %></span></h2>
				<ul>
					<% @songcomments.each do |songcomment| %>
					<li>
						<% @users.each do |user| %>
						<% if user.id == songcomment.user_id %>
						<h3 class="byline"><span class="date"><%= songcomment.created_at %></span> By <span class="user"><%= user.username %></span></h3>
						<% end %>
						<% end %>
						<div class="comment-body">
							<%= songcomment.content %>
						</div>					
					</li>
					<% end %>
				</ul>
				<% end %>
				<% end %>
				<% end %>
			</div>
			<% end %>
		</div>
	</article>
	<article class="other-songs">
		<h1>Other Songs being Worked on</h1>
		<ul>
			<% if @songs && @songs.size != 0 %>
			<% @songs.each do |song| %>
			<% if song.recorded == true && song.current == false %>
			<li>
				<%= link_to(song.name,  song_path(song)) %>
			</li>
			<% end %>
			<% end %>
			<% end %>
		</ul>
	</article>
</section>

<section class="users">
	<h1>Users</h1>
	<ul>
		<% if @users && @users.size != 0 %>
		<% @users.each do |user| %>
		<li><%= link_to(user.username, user_path(user)) %></a></li>
		<% end %>
		<% end %>
	</ul>
</section>

app/views/pages/home.html.erb
<section class="explanation-text">
	<article class="what-it-is">
		<p><strong>This is a musical experiment.</strong> The goal is to crowd-source the recording of an entire album, based on existing demo recordings of 15 amateur tracks.</p>
	</article>

	<article class="instructions">
		<h1>To Participate:</h1>
		<ol>
			<li><strong>Listen</strong> to the tracks</li>
			<li>Pick a <strong>song</strong> and <strong>part(s)</strong> to play</li>
			<li><strong>Sign up</strong> to record it</li>
		</ol>
	</article>

	<article class="how-it-works">
		<h1>How does it work?</h1>
		<p><strong>If the session goes well</strong>, it will be used in the final mix, and you'll be given a login and password for the "Member's Only" section of the site. There, you can hear the current mixes for all the works in progress, give feedback and participate in the making of the rest of the album.</p>
		<p><strong>Once the whole album is recorded</strong>, we will release it in digital and CD format. Everyone who plays on the album gets a spot in the liner notes and on the site for a short bio, picture, and url to your site. Also, you'll get appropriate royalties for your contribution to the album.</p>
		<p><strong>Thanks for checking it out! Hope to hear from you real soon.</strong></p>
	</article>

	<section id="mp3Player" data-folder="music" class="player">
	
		<audio id="mp3Player-player">
			<source id="mp3Player-mp3" src="" />
			<p class="no-html5">Your browser doesn\'t support HTML5 audio</p>
		</audio>

		<div id="mp3Player-controls" class="mp3Player-group playerControls">
			<div id="mp3Player-buttons-container">
				<button id="mp3Player-prev" class="mp3controls disabled">Prev</button>
				<div id="mp3Player-play-pause">
					<button id="mp3Player-play" class="mp3controls">Play</button>
					<button id="mp3Player-pause" class="mp3controls display-off">Pause</button>
				</div>
				<button id="mp3Player-next" class="mp3controls disabled">Next</button>
			</div>

			<div id="mp3Player-progress-container" class="mp3Player-group progressContainer">
				<span id="mp3Player-currentTime"></span>
				<div id="mp3Player-progress" class="loaded"></div>
				<span id="mp3Player-remainingTime"></span>
			</div>

			<div id="mp3Player-volume-container" class="mp3Player-group">
				<span id="mp3Player-min-volume"></span>
				<div id="mp3Player-volume"></div>
				<span id="mp3Player-max-volume"></span>
			</div>
		</div>
	
		<% if @songs && @songs.size != 0 %>
		<table id="mp3Player-table">
			<thead>
			<tr>
				<th>Song</th>
				<th>Part(s)</th>
			</tr>
			</thead>
			<tbody>
		<% @songs.each do |song| %>
		<% if song.active == true %>
			<tr class="song" data-file="<%= song.file %>">
				<td class="name"><%= song.name %></td>
				<td>
					<ul>
			<% if @assignments && @assignments.size != 0 %>
			<% @assignments.each do |assignment| %>
			<% if assignment.song_id == song.id && assignment.user_id != 1 %>
				<li class="part"><%= part(assignment.part_id) %></li>
			<% end %>
			<% end %>
			<% end %>
					</ul>
				</td>
			</tr>
		<% end %>
		<% end %>
		</table>
		<% end %>
		</tbody>
	</section>

	<section class="request form">
		<%= render "form_home" %>
		<button class="show-hide">Sign Up and Play</button>
	</section>
	
<section>