config/routes.rb
Strangerdanger::Application.routes.draw do
  resources :users, :user_sessions, :songs, :parts, :comments, :requests, :assignments
    match 'login' => 'user_sessions#new', :as => :login
    match 'logout' => 'user_sessions#destroy', :as => :logout
    match '/backyard',    :to => 'pages#backyard'
    match '/admin',    :to => 'pages#admin'
    
    root :to => 'pages#home'
    

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stranger Danger</title>
  <%= stylesheet_link_tag :all %>
  <link href='http://fonts.googleapis.com/css?family=Slackey' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Luckiest+Guy' rel='stylesheet' type='text/css'>
  <script type="text/javascript" charset="utf-8">var ROOT_PATH = "<%= root_path %>";</script>
  <%= javascript_include_tag "jquery.min" %>
  <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>
  <%= javascript_include_tag "jquery.livequery" %>
  <%= javascript_include_tag "jquery_ujs" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "mp3player" %>
  <%= csrf_meta_tag %>
</head>
<body>
	<div class="wrapper">	
		<header>
			<hgroup>
				<h1><%= link_to("Stranger Danger", "/") %></h1>
				<h2>A NYC Music Co-op</h2>
			</hgroup>
			
			<nav class="user">
				<ul>
				<% if checkusers(current_user) %>	
					<li><%= link_to(current_user.username, edit_user_path(current_user.id)) %></li> 
				    <li><%= link_to("Logout", :logout) %></li>
					<% if checkadmin(current_user) %>
				  		 <li><%= link_to("Admin Section", admin_path) %></li>
					<% end %>
				<% end %>

				</ul>
			</nav>
			<nav class="site">
				<ul>
					<li><%= link_to("Backyard", backyard_path, :class => "backyard-link") %></li>
				<% if request.path_parameters[:action] != "home" %>
					<li><%= link_to("Songs", songs_path) %></li>
					<li><%= link_to("Users", users_path) %></li>
				<% end %>
				</ul>
			</nav>			
		</header>
	
		<div class="body">
			<%= yield %>
		</div>
	
		<footer>
			<span class="contact">contact: <%= link_to("info@strangerdanger.com", "mailto:info@strangerdanger.com") %></span>
			<span class="copyright">&copy; 2011</span>
		</footer>
	</div>
</body>
</html>